parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true

plugins:
  - '@typescript-eslint'

extends:
  - standard
  - plugin:react/recommended
  - plugin:@typescript-eslint/eslint-recommended

rules:
  max-len: [error, 120]
  no-unused-vars: off
  no-use-before-define: off
  '@typescript-eslint/no-unused-vars': error
  '@typescript-eslint/no-use-before-define': error

settings:
  react:
    version: detect
