processorssors:
  - stylelint-processor-styled-components

extends:
  - stylelint-config-recommended
  - stylelint-config-rational-order
  - stylelint-config-styled-components

rules:
  plugin/rational-order:
    - true
    - empty-line-between-groups: true
